apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesome-backend
  template:
    metadata:
      labels:
        app: awesome-backend
    spec:
      containers:
      - name: backend
        image: harbor.allocsoc.net/awesome-crawler/awesome-backend:ea34d662a76237e8c9124bcd6c3989edc63a7b39
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_DEFAULT_REGION
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: S3_BUCKET
        - name: S3_KEY
          value: "data.json"
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 20
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 100
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: awesome-backend-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: awesome-backend
