apiVersion: batch/v1
kind: CronJob
metadata:
  name: awesome-crawler-job
  namespace: awesome-crawler
spec:
  schedule: "0 0 * * *"  # Every day at 00:00
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600  # 1 hour timeout
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: awesome-crawler
            image: harbor.allocsoc.net/awesome-crawler/awesome-crawler:d7ec44099c949b2b91603a57c573c96460e002d8
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: AWS_DEFAULT_REGION
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: S3_BUCKET
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "1024Mi"
                cpu: "1000m"
          restartPolicy: OnFailure
