name: Test

on:
  pull_request:
    paths:
      - 'crawler/**'
  push:
    branches: main
    tags: "*"
    paths:
      - 'crawler/**'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build crawler image even if no code changes'
        required: false
        default: 'false'
        type: boolean

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Setup Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.9
  #
  #     - name: Install dependencies with pipenv
  #       run: |
      #     pip install pipenv
      #     pipenv install --deploy --dev
      #
      # - run: pipenv run isort --recursive --diff .
      # - run: pipenv run black --check .
      # - run: pipenv run flake8
      # - run: pipenv run mypy
      # - run: pipenv run pytest --cov --cov-fail-under=100
  docker-image:
    runs-on: ubuntu-latest
    if: github.event.inputs.force_build == 'true' || github.event_name != 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.allocsoc.net
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build, tag, and push image to Harbor
        uses: docker/build-push-action@v5
        with:
          context: ./crawler
          push: true
          tags: harbor.allocsoc.net/awesome-crawler/awesome-crawler:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-manifests:
    needs: docker-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image in deployment
        run: |
          NEW_IMAGE=harbor.allocsoc.net/awesome-crawler/awesome-crawler:${{ github.sha }}
          sed -i "s|image: .*|image: ${NEW_IMAGE}|" k8s/awesome-crawler-cronjob.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/awesome-crawler-cronjob.yaml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update awesome-crawler image to ${{ github.sha }}"
            git push
          fi
